name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: riza
          POSTGRES_PASSWORD: empty
          POSTGRES_DB: ngobrolin_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.18'
          otp-version: '27.0'

      - name: Install Dependencies
        run: mix deps.get

      - name: Prepare DB
        run: mix ecto.create && mix ecto.migrate

      - name: Run Tests
        run: mix test